
version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: community_portal
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.7
    environment:
      MEILI_NO_ANALYTICS: 'true'
    ports:
      - '7700:7700'
volumes:
  pgdata:
